// Job
export const JOB_FETCH_SUCCESS = 'JOB_FETCH_SUCCESS'
export const JOB_FETCH_ALL_SUCCESS = 'JOB_FETCH_ALL_SUCCESS'
export const JOB_UPDATE_ACTIVE_SUCCESS = 'JOB_UPDATE_ACTIVE_SUCCESS'
export const JOB_UPDATE_CRON_SUCCESS = 'JOB_UPDATE_CRON_SUCCESS'
export const EXECUTOR_FETCH_ALL_SUCCESS = 'EXECUTOR_FETCH_ALL_SUCCESS'
export const JOB_CREATE_SUCCESS = 'JOB_CREATE_SUCCESS'

// Input
export const INPUT_UPDATE_SUCCESS = 'INPUT_UPDATE_SUCCESS'
export const INPUT_CREATE_SUCCESS = 'INPUT_CREATE_SUCCESS'
export const INPUT_DELETE_SUCCESS = 'INPUT_DELETE_SUCCESS'

// Task
export const TASK_FETCH_BY_JOB_SUCCESS = 'TASK_FETCH_BY_JOB_SUCCESS'
export const TASK_SWAP_SEQ_SUCCESS = 'TASK_SWAP_SEQ_SUCCESS'
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS'
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS'

// Error
export const ERROR_TRIGGERED = 'ERROR_TRIGGERED'
export const CLEAR_FLASH = 'CLEAR_FLASH'

// Test
export const TEST_POLL_SUCCESS = 'TEST_POLL_SUCCESS'
export const TEST_POLL_ERROR = 'TEST_POLL_ERROR'
export const TEST_INITIATE_SUCCESS = 'TEST_INITIATE_SUCCESS'

// Task
export const RESULT_FETCH_BY_JOB_SUCCESS = 'RESULT_FETCH_BY_JOB_SUCCESS'
