// Job
export const JOB_FETCH_SUCCESS = 'JOB_FETCH_SUCCESS'
export const JOB_UPDATE_ACTIVE_SUCCESS = 'JOB_UPDATE_ACTIVE_SUCCESS'
export const EXECUTOR_FETCH_ALL_SUCCESS = 'EXECUTOR_FETCH_ALL_SUCCESS'

// Input
export const INPUT_UPDATE_SUCCESS = 'INPUT_UPDATE_SUCCESS'
export const INPUT_SET_VALUE = 'INPUT_SET_VALUE'

// Task
export const TASK_FETCH_BY_JOB_SUCCESS = 'TASK_FETCH_BY_JOB_SUCCESS'
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS'
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS'

// Error
export const ERROR_TRIGGERED = 'ERROR_TRIGGERED'
export const CLEAR_FLASH = 'CLEAR_FLASH'
